### ISSUE TITLE
ungoogled Chromium not updating

### ISSUE THREAD

**Issue by nsiti** [iklevente/ChromiumForWindows#9]
Hi, I'm a relatively new user of Chromium for Windows. My Chromium version is stuck at 88.0.4324.150 (Official Build) (64-bit) on all three devices I have your software installed on. I have restarted Chromium and rebooted the computers but still no updates. Is there a trick to getting Chromium to update to the latest version? Thanks a lot for your effort on this project.

**Comment by iklevente** [comment]
Hi! I do not know what causes the issue, but try to delete your chromium build manually by going to your `C:\Users\%username%\AppData\Local\Chromium\` folder and delete the ungoogled-chromium-* folder, as well as the versioninfo.txt file.
After that try to launch ChromiumLauncher.exe and it should redownload the latest ungoogled chromium.

**If that doesn't work**
Go to your `Control Panel\Programs\Programs and Features` site and delete everything that's related to Chromium.
Then delete everything from `C:\Users\%username%\AppData\Local\Chromium\` **except** your User Data folder, in case you don't want your bookmarks, saved passwords and etc to get deleted.

Let me know if this resolved the issue, if not I'm here to help in any way I can.

**Comment by nsiti** [comment]
Hi, your first suggestion of removing the chromium build manually and re-running ChromiumLauncher updated the browser to the latest version. Thanks. I'll keep track of future updates to see if they are automatically installed.

**Comment by iklevente** [comment]
The default browser issue is now fixed in the latest release! (1.5.4)
Please do the required steps (mentioned in the release note) to fix it if you have problems with it too!

Sorry for the inconvenience! The new registry feature in Marmaduke's Chromium build broke the updater.
I am working on an installer dedicated to ChromiumForWindows and a Settings interface where you will be able to choose different builds (normal, ungoogled, raw, etc...) which will be more convenient even for uninstalling as well.
If everything goes right that should be the last huge update and the software would be capable of updating itself.

Thank you for your understanding and thank you for using the software!

**Comment by nsiti** [comment]
Thanks a lot for the fix and follow-up!

**Comment by nsiti** [comment]
Hi, following-up on this. My ungoogled chromium was not updated to the latest version on any of my computers. I have followed the hotfix instructions. Can you please investigate and confirm? Thanks.

**Comment by iklevente** [comment]
I don't know the reason. It works perfectly on my end. Sorry for the unconvenience.

I've noticed that the publisher now provides installers as executables too. (Not only .7z files) so I'm going to switch the updater engine tomorrow to work with that.

Hopefully that will help too, but the only thing that can cause the app to have a bug like that is that something is not right in the C:\Users\%USER%\AppData\Local\Chromium\ folder.

Here is my folder so you can see what's in it: https://imgur.com/a/XXBEOW9

Deleting versioninfo.txt, latest_ungoogled_chromium.7z, and ungoogled-chromium-Win64 folder should fix the problem.
If you see any other folders that you don't see on the screenshot and I didn't mention you might want to delete those too.

If it's still not updating, I'm still happy to help here on GitHub and even on Discord voice chat/screen share if needed.

**Comment by nsiti** [comment]
Hi, I tried to do the update as you advised above, but it didn't work. My Chromium folder was identical to yours. In fact, it did the update after deleting the 3 files you listed, but Chromium would not launch even after a reboot. I had to follow the hotfix update instructions to get the latest version of Chromium to run. Anyway, now I am updated. The only thing I wanted to mention is that I only have winrar installed, not 7zip, in case it makes a difference. Thank you.

**Comment by iklevente** [comment]
7zip is bundled with the updater so you don't need to download it manually. It's in the Resources folder inside the Chromium directory. That is what you see every time coming up as a command prompt for some seconds when there is an update and it needs to extract it.

Anyways I'm glad that it works now. So sorry for the inconvenience.

PS.: One problem could be that you were trying to run chrome.exe not ChromiumLauncher.exe and that's why it was not updating. I don't know it's just an assumption.

**Comment by nsiti** [comment]
I was running the ChromiumLauncher.exe but it didn't work. I believe the installer may have been corrupted as it seemed to stop at the end. Wondering how to best proceed with my other 2 pc's which have the same issue? Will you be putting out another hotfix to handle the executable version of the chromium builds? If so, I'll wait. It's not like I need the latest version, just wanting to fix the issue for the long term. Thanks for your assistance.

**Comment by iklevente** [comment]
I will tomorrow! I'll try to be as fast as possible. I will also test them in my virtual machines to find if there are errors.

It shouldn't be complicated though. I am using the "googled" Hibbiki version and because that is based on the executable version for a very long time now, I don't have any problems with it.

Now ungoogled has the .exe too so I just need to copy paste the code and rewrite the download links for that. No more messing with 7zip. 😅

Thanks for your patience.

**Comment by iklevente** [comment]
I published the new release: https://github.com/iklevente/ChromiumForWindows/releases/tag/1.5.5
Each of them is working fine for me, even after forcing an update process.

You can reopen the case any time if you are having difficulties.

Also you can check/provide your updater log file (C:\Users\%username%\AppData\Local\Chromium\log\) here any time so finding the problem can be easier in the future.

**Comment by nsiti** [comment]
Hi, ungoogled Chromium is still not updating. Stuck at the previous version even though the log says otherwise.

Log:
Chromium directory exists.
versioninfo.txt is already exists!
https://github.com/macchrome/winchrome/releases/tag/v90.0.4430.72-r857950-Win64 is the current local version.
Local version is the same as latest version!
Exiting!
Starting Chromium...

**Comment by iklevente** [comment]
Yes, I've realised it. 😕

The problem was that Marmaduke didn't have a logical order in their release [filenames](https://github.com/macchrome/winchrome/releases). He changed it many times and therefore the updater broke. 

His new way now makes sense, so I could implement it into ChromiumForWindows 2.0. It should be quite future proof now.
The project has a completely rewritten backend and an easy build switcher functionality with an update notifier if manual update needed in the future. Check the gifs in README.md.
Download it from [here](https://github.com/iklevente/ChromiumForWindows/releases/latest) following the instructions.
Hopefully we won't hassle with this anymore.

Thanks for using the product and thanks for your patience.

**Comment by nsiti** [comment]
Terrific, thanks!

**Comment by iklevente** [comment]
Hey, I forgot the code which adds the updater to the registry, so it can autorun at startup and check for updates. 😅
I'm sorry this was totally my fault.
I updated the [release](https://github.com/iklevente/ChromiumForWindows/releases/latest) with a description about how to add it to the Registry.

I'm working on CFW 2.1 which will fix this issue, will support more builds from https://chromium.woolyss.com/ and will have the Material Design Installer included that will automatically do all the cleanup and update process.
Hopefully I'll be done with it by the next week. The new Chromium Settings UI should notify you in the bottom right corner if the new update will be ready.
